services:
  registry:
    image: registry:2
    container_name: registry
    restart: unless-stopped
    environment:
      REGISTRY_STORAGE_DELETE_ENABLED: "true"
    volumes:
      - ./registry_data:/var/lib/registry
    networks:
      - proxy
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.registry-api.rule=Host(`registry.localhost`) && PathPrefix(`/v2`)"
      - "traefik.http.routers.registry-api.entrypoints=web"
      - "traefik.http.services.registry-api.loadbalancer.server.port=5000"

  registry-ui:
    image: joxit/docker-registry-ui:latest
    container_name: registry-ui
    restart: unless-stopped
    environment:
      - REGISTRY_URL=http://registry.localhost
      - SINGLE_REGISTRY=true
      - PROXY=true
      - DELETE_IMAGES=true
      - SHOW_CONTENT_DIGEST=true
    networks:
      - proxy
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.registry-ui.rule=Host(`registry.localhost`)"
      - "traefik.http.routers.registry-ui.entrypoints=web"
      - "traefik.http.services.registry-ui.loadbalancer.server.port=80"

networks:
  proxy:
    external: true
