services:
  shared-postgres:
    image: postgres:15-alpine
    container_name: shared_postgres
    restart: unless-stopped
    environment:
      POSTGRES_USER: ${DB_USER:-postgres}
      POSTGRES_PASSWORD: ${DB_PASSWORD:-11091998}
      POSTGRES_DB: postgres
    ports:
      - "5432:5432"
    volumes:
      - shared_postgres_data:/var/lib/postgresql/data
    networks:
      - proxy

volumes:
  shared_postgres_data:

networks:
  proxy:
    external: true
